### ISSUE TITLE
Handle init containers.

### ISSUE THREAD

**Issue by mdgreenwald** [mdgreenwald/push-deploy#4]
If a deployment has init containers, we need to be able to handle that case. Presently we would have no way to update init-containers.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
```
